### ISSUE TITLE
camera thingy moved into chest when walking with the phys/gravity gun

### ISSUE THREAD

**Issue by fiestajr** [VictorienXP/gmod-enhanced-camera-2#15]
https://user-images.githubusercontent.com/86935523/124403672-2d503580-dcfd-11eb-8db4-3b690a7b790b.mp4

yeah as you see in dis video, something clearly messed up. this only happens with the phys and gravity gun. nothing else

**Comment by fiestajr** [comment]
sorry for the Microsoft PowerPoint. I accidentally posted that instead of the video here is the video instead

https://user-images.githubusercontent.com/86935523/124405481-6213bb00-dd04-11eb-8213-92a89c2fe7b6.mp4

**Comment by VictorienXP** [comment]
I'm not really sure what's going on with your game but you should try to disable other addons to see if it helps.

**Comment by fiestajr** [comment]
ight
