### ISSUE TITLE
Addon resets camera height after death

### ISSUE THREAD

**Issue by Dasarathu** [VictorienXP/gmod-enhanced-camera-2#24]
My playermodel is extremely small. After I died the camera was at normal height and basically pulled up my entire body to camera height. any fixes?

**Comment by VictorienXP** [comment]
I believe this is caused by some others addons.

Try to isolate other addons until it doesn't happen anymore.

Feel free to reopen this issue if you know which addon is doing this.

Running and pasting output of `ec2_debug_print_hooks_sv` and `ec2_debug_print_hooks_cl` could help.

**Comment by MalturTA** [comment]
Hello! I had similar issue, but after countless hours of checking addons one-by-one, i found out, that it is fault of addons, that ship their custom animations for their playermodels (Or at least i think so).

Addon, that was causing issues for me is [\[PLAYERMODEL\] Griffin ARK:survival evolved](https://steamcommunity.com/sharedfiles/filedetails/?id=2793830628)

AFAIK "Dynamic Height + Crouch Fix" has similar issue, with exact addon. As quick fix, there was suggested turning off and on dynamic camera height calculations.
So, maybe add mode, that re-calculates camera height on every respawn, as quick solution?
