### ISSUE TITLE
I get errors with certain playermodels

### ISSUE THREAD

**Issue by Duscara** [VictorienXP/gmod-enhanced-camera-2#33]
I have no idea why, but switching to certain playermodels (like Dewritos from a different mod on the Steam Workshop) generates what I presume is an error either every frame or every few frames. The yellow part telling me there are errors never turns white, indicating that the errors repeat themselves a lot.

**Comment by VictorienXP** [comment]
Please copy and paste the error from the Problems menu ("Lua Errors" tab)
![image](https://user-images.githubusercontent.com/1633366/173355648-2b607d84-3d1c-47f5-a399-a609dfbed610.png)

**Comment by Duscara** [comment]
![20220615094051_1](https://user-images.githubusercontent.com/65032940/173855545-833ebcd1-e8f3-4ca7-9e48-a5079d0e9559.jpg)
If you can see this, will this work? I know it's not from the Problems task, but it is from the console spamming errors.

**Comment by VictorienXP** [comment]
Thanks for the screenshot!

This is weird. I'm not able to replicate this issue... I'm not really sure what is going on.
I'll try to make a mitigation based on the specific Lua error you have so it doesn't spam anymore.

I might not be able to publish a Steam Workshop update until next month.
So if that's the case you can try to download latest version from GitHub manually.

**Comment by Duscara** [comment]
It may have been because I was loading it on a map with lots of reflections. The playermodel doesn't usually cause problems and didn't when I loaded into the map as that model.
