### ISSUE TITLE
2 more hands showing up while using Modern Warfare 2019 Pistol Swep

### ISSUE THREAD

**Issue by Minhnhut90** [VictorienXP/gmod-enhanced-camera-2#36]
Every time I sprint, swim, it shows 2 more hands, and I couldn't find what is conflicting it.

I disable my mods and just only enable Enhanced Camera, Modern Warfare 2019 Pistol Swep, and Modern Warfare Base, but when I start the game, and I sprint, swim, and it worked with the Modern Warfare 2019 Pistol Swep, but I still can't find what is conflicting it.
When I slide with Quick Slide it does that one thing where you are done sliding and
Sharpeye? Life-mod? IK-foot? Draconic-Base? xdReanimsBase? Vmanip-Mods? Quick-Slide? TFA-Smod-Kick-Modified? Ulib? ULX?    
Contextual-Player-Animations? Simple-Leaning? Other-Modern-Warfare-2019-Swep-Guns? Dynamic-Height-+-Crouch-Fix?
NPC-Ragdoll-NoCollide-V2? And I don't know because those are not only one's that are in my mods, but if this can be fix, and if you made a mod that didn't show hands it would be great, but it would be kind of disrespectful if ask you to do it, but if you do it, if you fixed the hand problem, thanks.

**Comment by Minhnhut90** [comment]
I don't know what mod that is conflicting the enhanced camera 2 mod, I listed a much of mods that I think is conflicting it, but it can't be a much of mods like I listed that is conflicting the mod Enhanced Camera 2 and Modern Warfare 2019 Pistol Swep, and a mod is getting in the way when I use Enhanced Camera 2 with Modern Warfare 2019 Pistol Swep when i sprint and Swim or flinging yourself, I like your mod but I just don't like how it has 4 hands when I sprint with Modern Warfare 2019 Pistol Swep gun.

**Comment by VictorienXP** [comment]
I believe you have many addons that may conflict with the Enhanced Camera 2, for example (based on name):
* Dynamic-Height-+-Crouch-Fix
* Quick-Slide
* IK-foot
* xdReanimsBase

I would suggest trying another viewmodel addon like GmodLegs 3 for example instead of Enhanced Camera 2 if that can be of any help.

**Comment by Minhnhut90** [comment]
I like this mod it is realistic, can't just delete the mod because it has a little bug.
it's probably the custom modern warfare base weapons because enhanced camera 2 only works on the original not custom MW2019 swep pack

**Comment by VictorienXP** [comment]
Could you sent that addon link pls?
