### ISSUE TITLE
Enhanced Camera clips into hair when using TFA branch of weapons

### ISSUE THREAD

**Issue by AngelDustTheProstitute** [VictorienXP/gmod-enhanced-camera-2#43]
Enhanced camera 2 has a very very nasty habit of clipping hair, maws, and snouts inside itself , so I tried 3, no dice.
Only happens with certain weapons two, which is quite odd.
 
![garrysmod enchancedcamera 2024](https://github.com/VictorienXP/gmod-enhanced-camera-2/assets/159074640/688bff38-b6d1-43a3-bb44-1e2b0f27b472)
Does this look enhanced?
 
![gmod enhanced camera 2024 2](https://github.com/VictorienXP/gmod-enhanced-camera-2/assets/159074640/ee2d4fd3-49f2-4447-8281-07932253d9c6)
Second verse, same as the first.

**Comment by VictorienXP** [comment]
Please provide links to the addons involved here (weapons, playermodel...)

**Comment by AngelDustTheProstitute** [comment]
Fetching the deets, please wait a quick moment while I load an low LOD map.

**Comment by AngelDustTheProstitute** [comment]
Combine enhanced camera with the following: 
 

https://steamcommunity.com/sharedfiles/filedetails/?id=3044793076 Nika Sharkeh V2 - [Playermodel] (A simple port from an SFM / blender rig, ain't nobody got time to make it fully sfw, considering it's only real source is from warfaresmachines edit)
 
https://steamcommunity.com/sharedfiles/filedetails/?id=2509111012 [TFA] Call of Duty Infinite Warfare Weapons (Requires TFA base!)
 
https://steamcommunity.com/sharedfiles/filedetails/?id=770990581 (Simple Third person keybind, CTRL + SHIFT)
 
https://steamcommunity.com/sharedfiles/filedetails/?id=207948202 (Pre-requisite to use simple third person keybind) 
 
https://steamcommunity.com/sharedfiles/filedetails/?id=2203217139 (Your addon)
