### ISSUE TITLE
When I crouch my camera stays in the standing position 

### ISSUE THREAD

**Issue by TheFurry129** [VictorienXP/gmod-enhanced-camera-2#9]
Also you can see pyro's mask in the "femme pyro playermodel" mod

**Comment by VictorienXP** [comment]
Other addons may create conflicts. Could you dump your addon list so I can better identify what is going on?
Subscribe to [this tool](https://steamcommunity.com/sharedfiles/filedetails/?id=2443976641), start a game then run `dump_addon_list_markdown` in the [console](https://steamcommunity.com/sharedfiles/filedetails/?id=627640216). 
It will output your addon list in Markdown in the garrymod/data folder. Then you can upload it here.
If you can, make sure to remove the `.txt` in the filename so it finish with `.md` and not `.txt` when uploading it here.

I'll try to take a look at this once I'm available.

**Comment by TheFurry129** [comment]
[addon_list.md](https://github.com/VictorienXP/gmod-enhanced-camera-2/files/6489366/addon_list.md)

**Comment by TheFurry129** [comment]
[addon_list.md](https://github.com/VictorienXP/gmod-enhanced-camera-2/files/6489372/addon_list.md.txt)

**Comment by VictorienXP** [comment]
Sorry @TheFurry129 you just have too much addons and I don't have the time to go through everything.

But I've just added (64e607d1d7794ff640c9815e0ab8db543e89a86e) a console command that will trace any usage of the relevant functions in the console. 
Just type `ec2_debug_enable_sv` in the console to enable this.

Please try to find the addon that is messing with the camera view yourself and/or please provide any traces that would show up in the console. 
Don't forget to try other playermodels or any playermodel that may change the view height.

Also if you want a fix for the "femme pyro playermodel" addon, please open another issue only for it.

**Comment by TheFurry129** [comment]
understood and thank you for your time
